FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

#  docker run -ti -p 3000:3000 -v /app/node_modules -v $(pwd):/app 7fb41a316667 -e CHOKIDAR_USEPOLLING=true