apiVersion: v1 
kind: Secret
metadata:
  name: postgres-secret
spec:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ebzdag/fib-server
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: "postgres"
            - name: PGHOST
              value: postgres-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: pgpassword
                    key: pgpassword
          resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
  