apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    name: web
spec:
  containers:
  - name: client
    image: ebzdag/multi-client
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 31515

