apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: client
        image: ebzdag/fib-client
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

# image: stephengrider/multi-client
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 31515
